### ISSUE TITLE
Django Models Design

### ISSUE THREAD

**Issue by danielmuringe** [Chuka-uni-engineers/Django-Dashboard-And-API#4]
Can I start designing Django model as designed?

**Comment by dynamic2code** [comment]
Yes you can. Just make a new branch make your changes then make a pull request.

**Comment by deluxesande** [comment]
What models are we working on??

**Comment by Panther-12** [comment]
> What models are we working on??

User, projects, communities @dynamic2code can list other required models

**Comment by dynamic2code** [comment]
sorry for the long wait, graduation preparation. You can get all the models here https://github.com/Chuka-uni-engineers/Django-Dashboard-And-API/blob/main/chuka_app_relational_diaghram.png
