### ISSUE TITLE
Wireframes Request

### ISSUE THREAD

**Issue by danielmuringe** [Chuka-uni-engineers/Django-Dashboard-And-API#5]
Does someone have the wireframes used for the Entity Relationship Design. There seems to be some gaps in the design

**Comment by Panther-12** [comment]
@danielmuringe What kind of gaps exist in the design..

**Comment by Panther-12** [comment]
We'll compile from the various models and relationships team members come up with. This will be done through an online google meet session. The ERD Diagram for the final database schema will be done then
